### ISSUE TITLE
Throw away GreenDAO

### ISSUE THREAD

**Issue by hkurokawa** [hotchemi/dexfm-android#5]
I don't know why you chose GreenDAO. I'm afraid it's a blocker to prevent us from moving to Kotlin. How about [Android-Orma](https://github.com/gfx/Android-Orma)?

**Comment by hotchemi** [comment]
Well, the reason is that I use it heavily in the work so I wanna follow up the latest news in my private time.
But yeh, I'm also checking requery and SqlBrite right now.

**Comment by hotchemi** [comment]
@hkurokawa I've been thinking and how about realm?
I'd been hesitating using it in production since that means we say good-bye to sqlite and use ndk that increases apk size a lot.
But this is just a toy app, and I heard we can use realm with Kotlin and RxJava nicely.

Orma is great, but I guess it won't be a "mainstream" of worldwide development style...and it's already used in droidkaigi app. I wanna tackle to different style.

**Comment by hotchemi** [comment]
Actually GreenDAO currently works well, so it's not a development blocker now.

**Comment by hkurokawa** [comment]
I agree. Only I'm concerning about how much I have to deal with the bridge code between Java and Kotlin. IMO, we should move to 100% Kotlin as long as we could. I agree with the decision to use Realm, which I've been interested in much.

Anyway, this is your repository and you can do as you like :-) I was just wondering. Thanks!

**Comment by hotchemi** [comment]
After evaluating the Realm, I decided to adopt StorIO instead of that.
There are a few reasons but the biggest one is I'm not a huge fun of its interface...and Realm still has some restrictions like thread model or so.
Instead of that I finally choose https://github.com/pushtorefresh/storio.
It's a little bit similar to SqlBrite but it also does object mapping. It's not a ORM but do some abstraction and support build query with safe way. I really like this idea:D
